# Generated by Django 6.0 on 2025-12-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0001_initial'),
    ]

    operations = [
    ]
