# Generated by Django 6.0 on 2025-12-13 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0002_auto_20251212_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Elections.election'),
        ),
    ]
